; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    mikalhart/TinyGPSPlus
lib_ldf_mode = deep+
build_flags = 
    -I lib/uFCoder/include
    -L lib/uFCoder/lib
    -l ufcoder
    -Wno-pragmas
    -Wno-unused-variable
    -Wno-implicit-function-declaration
    -DDEBUG_PRINT=0
    -D_NO_FTDI=1
    -DESP_PLATFORM=1
    -DuFC_EXPORTS